# config.yaml - AI Video Upscaler Pro v2.0

# Server Configuration
server:
  host: "0.0.0.0"
  port: 7860
  share: false
  queue_max_size: 10
  auth:
    enabled: false
    username: "admin"
    password: "changeme"

# Models Configuration
models:
  base_path: "/app/models"
  auto_download: true
  cache_models: true

# Processing Configuration
processing:
  tile_size: 512
  tile_pad: 10
  pre_pad: 0
  clear_cache_interval: 50
  fp16: true
  batch_size: 1

# Output Configuration
output:
  codec: "libx264"
  preset: "medium"  # ultrafast, fast, medium, slow, veryslow
  crf: 18  # 0-51, menor = mejor calidad (18 es casi lossless)
  audio_bitrate: "320k"
  pixel_format: "yuv420p"
  max_width: 3840
  max_height: 2160

# Workspace Configuration
workspace:
  path: "/app/workspace"
  cleanup: true
  max_age_hours: 24
  max_size_gb: 100

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "/app/logs/app.log"
  max_size_mb: 100
  backup_count: 5

# Limits
limits:
  max_video_duration: 600  # segundos (10 min)
  max_file_size_mb: 2048   # 2 GB
  max_resolution: 1920     # ancho máximo input
