version: '3.8'

services:
  ai-video-upscaler:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-video-upscaler-pro:latest
    container_name: ai-video-upscaler-pro
    ports:
      - "7860:7860"
    volumes:
      - ./workspace:/app/workspace
      - ./models:/app/models
      - ./examples:/app/examples
      - ./logs:/app/logs
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - CUDA_VISIBLE_DEVICES=0
      - NUMEXPR_MAX_THREADS=16
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    stdin_open: true
    tty: true
    shm_size: '8gb'

networks:
  default:
    name: ai-video-upscaler-network
